// <auto-generated />
using System;
using System.Collections.Generic;
using HackYeah2025.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HackYeah2025.Migrations
{
    [DbContext(typeof(HackYeahDbContext))]
    [Migration("20251004200400_AddStatuEvent")]
    partial class AddStatuEvent
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoordinatorId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasDefaultValueSql("timezone('utc', now())");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Guid?>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Guid?>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoordinatorId")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Login")
                        .IsUnique();

                    b.HasIndex("OrganizerId")
                        .IsUnique();

                    b.HasIndex("VolunteerId")
                        .IsUnique();

                    b.ToTable("Accounts", (string)null);
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.AccountRole", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AccountRoles", (string)null);
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.AccountTask", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskItemId")
                        .HasColumnType("uuid");

                    b.HasKey("AccountId", "TaskItemId");

                    b.HasIndex("TaskItemId");

                    b.ToTable("AccountTasks");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Coordinator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Coordinators", (string)null);
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset?>("CompletedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EventStatus")
                        .HasColumnType("integer");

                    b.Property<decimal>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("LongDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganizerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTimeOffset>("RegisterDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ShortDescription")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2b4ae59e-7adf-4a95-a410-9ec118984d47"),
                            Address = "ul. Przemian 4",
                            City = "Warszawa",
                            DateFrom = new DateTimeOffset(new DateTime(2025, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            DateTo = new DateTimeOffset(new DateTime(2025, 4, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            EventStatus = 1,
                            Latitude = 50.067930m,
                            LongDescription = "Civic Lab 2025 to intensywny proces projektowy, w którym zespoły młodzieżowe pracują z mentorami nad realnymi wyzwaniami miast. Uczestnicy przejdą przez etap diagnozy problemu, prototypowania rozwiązań oraz przygotowania prezentacji przed jury złożonym z przedstawicieli samorządów i organizacji społecznych.",
                            Longitude = 19.983189m,
                            Name = "Civic Lab 2025",
                            OrganizerId = new Guid("4b1846cf-3c3a-4939-85f9-884f48216dfb"),
                            Place = "Centrum Innowacji Młodych",
                            RegisterDate = new DateTimeOffset(new DateTime(2025, 3, 10, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 0, 0, 0, 0)),
                            ShortDescription = "Trzydniowe laboratorium projektowe, w trakcie którego młodzież tworzy rozwiązania dla wyzwań lokalnych."
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.EventEventTopic", b =>
                {
                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventTopicId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId", "EventTopicId");

                    b.HasIndex("EventTopicId");

                    b.ToTable("EventEventTopics", (string)null);

                    b.HasData(
                        new
                        {
                            EventId = new Guid("2b4ae59e-7adf-4a95-a410-9ec118984d47"),
                            EventTopicId = new Guid("3acb29ab-38b3-4ce3-89ad-2fd25ed4a51c")
                        },
                        new
                        {
                            EventId = new Guid("2b4ae59e-7adf-4a95-a410-9ec118984d47"),
                            EventTopicId = new Guid("d46920c0-0b77-4a0e-8c1f-9af70906cb60")
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.EventTopic", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("EventTopics", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3acb29ab-38b3-4ce3-89ad-2fd25ed4a51c"),
                            Name = "innowacje społeczne"
                        },
                        new
                        {
                            Id = new Guid("d46920c0-0b77-4a0e-8c1f-9af70906cb60"),
                            Name = "edukacja obywatelska"
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Organization", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("Mission")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Programs")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Organizations");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5d1f3c76-7a10-4fb4-a4a1-0d5710a98b72"),
                            FoundedYear = 2012,
                            Location = "Centrum Aktywności Społecznej\nul. Solidarności 27\nWarszawa",
                            Mission = "Wspieramy młodych liderów w rozwijaniu projektów społecznych, łącząc edukację obywatelską z działaniem w terenie.",
                            Name = "Fundacja Młodzi Działają",
                            Programs = "inkubator projektów, mikrogranty sąsiedzkie, akademia wolontariatu",
                            Website = "https://mlodzi-dzialaja.pl"
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Organizer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Languages")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("OrganizationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("Specializations")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId");

                    b.ToTable("Organizers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4b1846cf-3c3a-4939-85f9-884f48216dfb"),
                            Email = "marta.zawadzka@mlodzi-dzialaja.pl",
                            FullName = "Marta Zawadzka",
                            Languages = "polski, angielski",
                            OrganizationId = new Guid("5d1f3c76-7a10-4fb4-a4a1-0d5710a98b72"),
                            Phone = "+48 501 222 198",
                            Role = "Koordynatorka programu",
                            Specializations = "partycypacja młodzieży, partnerstwa lokalne"
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("4d7a2d92-1d09-4e9e-98ed-9d3dc81f2df6"),
                            Name = "Wolontariusz"
                        },
                        new
                        {
                            Id = new Guid("a9a71dc8-3e5d-4c08-a6d5-7a80cd3607cf"),
                            Name = "Koordynator"
                        },
                        new
                        {
                            Id = new Guid("f9bc7305-3fa3-4c79-8e59-2f75cd288846"),
                            Name = "Organizator"
                        },
                        new
                        {
                            Id = new Guid("be0cb87d-54b9-4f6c-a2d4-0d174f37d0cd"),
                            Name = "Administrator"
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Tag", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Tags", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9a3e0ca5-579f-49ba-a479-76a519e5c08a"),
                            Name = "Integracja młodzieży"
                        },
                        new
                        {
                            Id = new Guid("0b93ef04-03ea-4bb8-8aa4-2a0d9c51bfb3"),
                            Name = "Wsparcie seniorów"
                        },
                        new
                        {
                            Id = new Guid("1a6d420a-4851-45ce-b756-609d0c48e1c6"),
                            Name = "Wydarzenia kulturalne"
                        },
                        new
                        {
                            Id = new Guid("1d8cb68b-20da-4c4c-93f0-326f0f7a086b"),
                            Name = "Edukacja obywatelska"
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.TaskItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("DateEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("DateStart")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("TaskItems");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Volunteer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Dictionary<string, string>>("Availability")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<Dictionary<string, string>>("Languages")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("PreferredRoles")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<Dictionary<string, string>>("Skills")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("Transport")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.ToTable("Volunteers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9f064bb8-162d-4e49-88f5-2e5f5f9a7ab8"),
                            Availability = new Dictionary<string, string> { ["tuesday_thursday"] = "Wtorki i czwartki 16:00 – 20:00", ["weekends"] = "Weekendy według ustaleń" },
                            Description = "Doświadczona wolontariuszka wspierająca projekty międzypokoleniowe oraz wydarzenia edukacyjne.",
                            Email = "julia.nowak@mlodzidzialaja.pl",
                            FirstName = "Julia",
                            Languages = new Dictionary<string, string> { ["Polski"] = "C2", ["Angielski"] = "C1", ["Ukraiński"] = "B1" },
                            LastName = "Nowak",
                            Phone = "+48 511 222 333",
                            PreferredRoles = "Koordynacja wolontariuszy, prowadzenie warsztatów, moderacja spotkań",
                            Skills = new Dictionary<string, string> { ["Komunikacja i moderacja"] = "Zaawansowany", ["Animacja czasu wolnego"] = "Średniozaawansowany", ["Pierwsza pomoc"] = "Podstawowy", ["Planowanie wydarzeń"] = "Zaawansowany" },
                            Transport = "Rower, komunikacja miejska, możliwość dojazdu do 20 km"
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.VolunteerDistinction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("VolunteerId");

                    b.ToTable("VolunteerDistinctions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("8d5fdf09-04ac-4b76-bbef-f5fb3787e6bf"),
                            Description = "Wyróżnienie za 120 godzin pracy z młodzieżą i seniorami w 2024 roku.",
                            Title = "Nagroda \"Wolontariusz roku\"",
                            VolunteerId = new Guid("9f064bb8-162d-4e49-88f5-2e5f5f9a7ab8")
                        },
                        new
                        {
                            Id = new Guid("9e0c6883-9461-4d6f-b6f2-f2de4f6dd0a4"),
                            Description = "Ukończony kurs Polskiego Czerwonego Krzyża, obejmujący scenariusze miejskie.",
                            Title = "Certyfikat z pierwszej pomocy",
                            VolunteerId = new Guid("9f064bb8-162d-4e49-88f5-2e5f5f9a7ab8")
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.VolunteerTag", b =>
                {
                    b.Property<Guid>("VolunteerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TagId")
                        .HasColumnType("uuid");

                    b.HasKey("VolunteerId", "TagId");

                    b.HasIndex("TagId");

                    b.ToTable("VolunteerTags", (string)null);

                    b.HasData(
                        new
                        {
                            VolunteerId = new Guid("9f064bb8-162d-4e49-88f5-2e5f5f9a7ab8"),
                            TagId = new Guid("9a3e0ca5-579f-49ba-a479-76a519e5c08a")
                        },
                        new
                        {
                            VolunteerId = new Guid("9f064bb8-162d-4e49-88f5-2e5f5f9a7ab8"),
                            TagId = new Guid("0b93ef04-03ea-4bb8-8aa4-2a0d9c51bfb3")
                        },
                        new
                        {
                            VolunteerId = new Guid("9f064bb8-162d-4e49-88f5-2e5f5f9a7ab8"),
                            TagId = new Guid("1a6d420a-4851-45ce-b756-609d0c48e1c6")
                        },
                        new
                        {
                            VolunteerId = new Guid("9f064bb8-162d-4e49-88f5-2e5f5f9a7ab8"),
                            TagId = new Guid("1d8cb68b-20da-4c4c-93f0-326f0f7a086b")
                        });
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Account", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Coordinator", "Coordinator")
                        .WithOne("Account")
                        .HasForeignKey("HackYeah2025.Infrastructure.Models.Account", "CoordinatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HackYeah2025.Infrastructure.Models.Organizer", "Organizer")
                        .WithOne("Account")
                        .HasForeignKey("HackYeah2025.Infrastructure.Models.Account", "OrganizerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HackYeah2025.Infrastructure.Models.Volunteer", "Volunteer")
                        .WithOne("Account")
                        .HasForeignKey("HackYeah2025.Infrastructure.Models.Account", "VolunteerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Coordinator");

                    b.Navigation("Organizer");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.AccountRole", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Account", "Account")
                        .WithMany("AccountRoles")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackYeah2025.Infrastructure.Models.Role", "Role")
                        .WithMany("AccountRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.AccountTask", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Account", "Account")
                        .WithMany("AccountTasks")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackYeah2025.Infrastructure.Models.TaskItem", "Task")
                        .WithMany("AccountTasks")
                        .HasForeignKey("TaskItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Event", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Organizer", "Organizer")
                        .WithMany("Events")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organizer");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.EventEventTopic", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Event", "Event")
                        .WithMany("EventEventTopics")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackYeah2025.Infrastructure.Models.EventTopic", "EventTopic")
                        .WithMany("EventEventTopics")
                        .HasForeignKey("EventTopicId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("EventTopic");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Organizer", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Organization", "Organization")
                        .WithMany("Organizers")
                        .HasForeignKey("OrganizationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organization");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.TaskItem", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Event", "Event")
                        .WithMany("TaskItems")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.VolunteerDistinction", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Volunteer", "Volunteer")
                        .WithMany("Distinctions")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.VolunteerTag", b =>
                {
                    b.HasOne("HackYeah2025.Infrastructure.Models.Tag", "Tag")
                        .WithMany("VolunteerTags")
                        .HasForeignKey("TagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HackYeah2025.Infrastructure.Models.Volunteer", "Volunteer")
                        .WithMany("VolunteerTags")
                        .HasForeignKey("VolunteerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tag");

                    b.Navigation("Volunteer");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Account", b =>
                {
                    b.Navigation("AccountRoles");

                    b.Navigation("AccountTasks");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Coordinator", b =>
                {
                    b.Navigation("Account");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Event", b =>
                {
                    b.Navigation("EventEventTopics");

                    b.Navigation("TaskItems");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.EventTopic", b =>
                {
                    b.Navigation("EventEventTopics");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Organization", b =>
                {
                    b.Navigation("Organizers");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Organizer", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Role", b =>
                {
                    b.Navigation("AccountRoles");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Tag", b =>
                {
                    b.Navigation("VolunteerTags");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.TaskItem", b =>
                {
                    b.Navigation("AccountTasks");
                });

            modelBuilder.Entity("HackYeah2025.Infrastructure.Models.Volunteer", b =>
                {
                    b.Navigation("Account");

                    b.Navigation("Distinctions");

                    b.Navigation("VolunteerTags");
                });
#pragma warning restore 612, 618
        }
    }
}
