name: Build Android Signed APK & AAB
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: build-android
  cancel-in-progress: false

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Decode Keystore
        run: |
          echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 --decode > app/my-release-key.keystore
        shell: bash

      - name: Verify keystore
        run: |
          ls -lh app/*.keystore
          keytool -list -v -keystore app/my-release-key.keystore -storepass ${{ secrets.ANDROID_KEYSTORE_PASSWORD }} || true
        shell: bash

      - name: Set gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: |
          ./gradlew assembleRelease \
            -PMYAPP_UPLOAD_STORE_FILE=my-release-key.keystore \
            -PMYAPP_UPLOAD_KEY_ALIAS=${{ secrets.ANDROID_KEY_ALIAS }} \
            -PMYAPP_UPLOAD_STORE_PASSWORD=${{ secrets.ANDROID_KEYSTORE_PASSWORD }} \
            -PMYAPP_UPLOAD_KEY_PASSWORD=${{ secrets.ANDROID_KEY_PASSWORD }}
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-build-apk
          path: |
            android/app/build/outputs/apk/release/*.apk
          if-no-files-found: ignore
