name: Build Android Signed APK & AAB
permissions:
  contents: read
  pull-requests: write
concurrency:
  group: build-android
  cancel-in-progress: false

on:
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: android

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Set gradlew executable
        run: chmod +x ./gradlew

      - name: Build APK
        run: |
          ./gradlew assembleRelease
        env:
          EXPO_PUBLIC_FIREBASE_API_KEY: ${{ secrets.EXPO_PUBLIC_FIREBASE_API_KEY }}
        shell: bash

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: android-build-apk
          path: |
            android/android/app/build/outputs/apk/release/*.apk
          if-no-files-found: ignore
