name: Deployment process
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select branch'
        required: true
        default: 'main'

jobs:
  build-frontend:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      branch: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
      event_name: ${{ github.event_name }}
      image_name: czerwony03/hackyeah2025_frontend
      context: ./frontend
      dockerfile: ./frontend/Dockerfile
      add_build_time: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}

  build-backend:
    uses: ./.github/workflows/docker-build-push.yml
    with:
      branch: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.branch || github.ref_name }}
      event_name: ${{ github.event_name }}
      image_name: czerwony03/hackyeah2025_backend
      context: ./backend/HackYeah2025.Backend
      dockerfile: ./backend/HackYeah2025.Backend/Dockerfile
      add_build_time: true
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  
  deploy:
    needs: [build-frontend, build-backend]
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}" | base64 -d > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ vars.DEPLOY_SSH_HOST }} >> ~/.ssh/known_hosts
          cat >> ~/.ssh/config <<EOF
          Host deploy-target
            HostName ${{ vars.DEPLOY_SSH_HOST }}
            User ${{ vars.DEPLOY_SSH_USERNAME }}
            Port ${{ vars.DEPLOY_SSH_PORT }}
            IdentityFile ~/.ssh/deploy_key
          EOF

      - name: Transfer docker-compose.prod.yml
        run: |
          scp docker-compose.prod.yml deploy-target:/home/${{ vars.DEPLOY_SSH_USERNAME }}/docker-compose.yml

      - name: Transfer ReverseProxy directory
        run: |
          rsync -avz ReverseProxy/ deploy-target:/home/${{ vars.DEPLOY_SSH_USERNAME }}/ReverseProxy/
          
      - name: Download backend image artifact
        uses: actions/download-artifact@v4
        with:
          name: czerwony03-hackyeah2025_backend

      - name: Load and transfer backend image
        run: |
          scp image.tar deploy-target:/home/${{ vars.DEPLOY_SSH_USERNAME }}/backend.tar
          ssh deploy-target "docker load -i /home/${{ vars.DEPLOY_SSH_USERNAME }}/backend.tar && rm backend.tar"

      - name: Download backend image artifact
        uses: actions/download-artifact@v4
        with:
          name: czerwony03-hackyeah2025_frontend
      
      - name: Load and transfer frontend image
        run: |
          scp image.tar deploy-target:/home/${{ vars.DEPLOY_SSH_USERNAME }}/frontend.tar
          ssh deploy-target "docker load -i /home/${{ vars.DEPLOY_SSH_USERNAME }}/frontend.tar && rm frontend.tar"

      - name: Reload Docker Compose
        run: |
          ssh deploy-target "docker compose up -d --remove-orphans --force-recreate"
